---
driver:
  name: hyperv
  parent_vhd_folder: D:\HyperVResources\VMs\BaseBox1
  parent_vhd_name: BaseBox1.vhdx
  vm_switch: ExternalSwitch
  memory_startup_bytes: 2GB

provisioner:
  name: chef_zero

transport:
  password: H0rnyBunny

verifier:
  name: pester

platforms:
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[ServerX4::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
